### ISSUE TITLE
Features/smoothing profiles

### ISSUE THREAD

**Issue by leahvschaffer** [fosterlab/PrInCE#4]
Hello, I noticed in calculate_features.R that smooth  and impute_NA are set to false when calling clean_profiles. However, in the paper/vignettes it says that the profiles are cleaned before feature generating steps like calculating Euc distance... is this intended?

![image](https://user-images.githubusercontent.com/16846041/134586154-4fb98dad-e3a2-4b6f-af21-dac0bbfc8a8d.png)

**Comment by GregStacey** [comment]
The argument naming is a little unclear, but even with `impute_NA=False` and `smooth=False`, clean_profiles() will still returned imputed profiles. `impute_NA` just turns on the impute_neighbours() function, and `smooth` applies a moving average to everything.

I'm not 100% sure what exactly what done for the paper+vignettes, but short answer, running clean_profiles() as above will still impute missing values with near-zero values.

```
> y = runif(50)
> y[sample(50,30)] = NA # make some missing values
> y2 = clean_profile(y, impute_NA = F, smooth = F, noise_floor = 0.05)
> ggplot(data.frame(fraction=rep(1:50,2), value=c(y2,y), type=c(rep("cleaned",50), rep("original",50))), aes(x=fraction, y=value, color=type)) + geom_point() + geom_line() 
```
<img width="862" alt="Screen Shot 2021-09-23 at 3 09 38 PM" src="https://user-images.githubusercontent.com/14293882/134590788-d4e262ff-0e1d-4329-92d9-76dfc1121741.png">

**Comment by leahvschaffer** [comment]
Hi Greg, OK thanks! This seems slightly different than what the vignette says (intro-to-prince.Rmd) FYI so I wasn't sure what was the intended feature input... it might not matter or affect output very much though! 
![image](https://user-images.githubusercontent.com/16846041/134594023-253efc4c-e785-46af-8d9f-a9d8b9a52191.png)

**Comment by GregStacey** [comment]
Ah right, in that case yes! The current version differs slightly from what's in intro-to-prince.Rmd. Specifically the current version's not imputing single missing values (inpute_NA=F) and it's not smoothing with a moving average (smooth=F).

In practice I've found that exactly how you clean the profiles isn't too important, as long as you're imputing missing values somehow.

Mike did a deeper dive on optimal ways to impute https://www.nature.com/articles/s41592-021-01194-4 (Fig. 2d), and he found imputing with zeros instead of near-zero noise was better, but we didn't know that at the time of publishing this prince paper.

**Comment by leahvschaffer** [comment]
OK great thank you for the info - that is helpful/good to know!!
